export enum APP_ROUTES_NAMES {
  BASE = '',
  BASE_FULL = '/',
  MAIN = 'main',
  MAIN_FULL = '/main',
  SETTINS = 'settings',
  SETTINS_FULL = '/main/settings',
  DESCRIPTION = 'descrtiption',
  DESCRIPTION_FULL = '/main/description',
  STATISTICS = 'statistics',
  STATISTICS_FULL = '/main/statistics',
  LOGIN = 'login',
  LOGIN_FULL = '/main/login',
  GAME = 'game',
  GAME_FULL = '/game',
  START = 'start',
  START_FULL = '/game/start',
  END = 'end',
  END_FULL = '/game/end'
}
